services: docker

before_install:
  - docker -v
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

install:
  - docker build -f Dockerfile -t ling-508/devnagri:latest .

script:
  - docker run -it ling-508/devnagri:latest python -m pytest tests
