version: "2"
services:
  app:
    build: .
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devanagari  # Add the database name
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
